all:
	make -C recognize all

recognize: 
	make -C recognize recognize

server_recognize:
	make -C recognize server_recognize

do_transformation:
	make -C recognize do_transformation

do_transformation.o:
	make -C recognize do_transformation.o

transformation.o:
	make -C recognize transformation.o

error_test:
	make -C recognize error_test

test_image_comparison:
	make -C recognize test_image_comparison

clean:
	make -C recognize clean

cleanall:
	make -C recognize cleanall
